from_latest_tag = true
ignore_merge_commits = false
ignore_fixup_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = []
pre = "alpha.*"
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = [
    "cargo check --package {{package}}",
    "cargo test --package {{package}}",
    "cargo set-version {{version}} --package {{package}}",
    "skaffold build --tag='{{version}}' --profile=['prodcuction'] --build-image=['{{package}}']",
    "skaffold deploy",
]
post_package_bump_hooks = [
    "git push",
]
tag_prefix = "v"

[git_hooks.pre-commit]
script = """
#!/bin/sh
cargo fix
"""

[commit_types]
fix = { changelog_title = "🐛 Bug Fixes", bump_patch = true }
merge = { changelog_title = "🔀 Merge branch", bump_minor = true }
feat = { changelog_title = "✨ New Features", bump_minor = true }
refactor = { changelog_title = "♻️ Code Refactoring", bump_patch = true }
chore = { changelog_title = "🎫 Chores & Maintenance", bump_patch = true }
perf = { changelog_title = "⚡ Performance Improvements", bump_patch = true }
ci = { changelog_title = "👷 Continuous Integration" }
ops = { changelog_title = "☁️ Operations & Infrastructure" }
build = { changelog_title = "📦 Build System", bump_patch = true }
docs = { changelog_title = "📝 Documentation" }
style = { changelog_title = "💄 Styles & Formatting" }
rollback = { changelog_title = "⏪ Rollbacks" }
test = { changelog_title = "🧪 Tests & Coverage" }

[changelog]
path = "CHANGELOG.md"
authors = []

[monorepo]
resolver = "Cargo"

[monorepo.packages.forma-core]
path = "adaptors/forma-core"
changelog_path = "CHANGELOG.md"
public_api = true

[monorepo.packages.forma-proc-macro]
path = "adaptors/forma-proc-macro"
changelog_path = "CHANGELOG.md"
public_api = true

[monorepo.packages.api-gateway]
path = "adaptors/api-gateway"
changelog_path = "CHANGELOG.md"
public_api = false
bump_order = 1

[monorepo.packages.auth-service]
path = "services/auth-service"
changelog_path = "CHANGELOG.md"
public_api = false
bump_order = 1
